name = "story-generator"
main = "worker.py"
compatibility_date = "2024-03-23"

[build]
command = "pip install -r requirements.txt"

[site]
bucket = "."

[env.production]
workers_dev = true

[[routes]]
pattern = "/*"
zone_id = "your-zone-id" 